spring:
  config:
    activate:
      on-profile:

  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

logging:
  level:
    root:
    com.trello.trello_api: